### ISSUE TITLE
Possible mistake in calculating Depositor Coin Price

### ISSUE THREAD

**Issue by dmtrbch** [soliditylabs/ZTM-Solidity-Code-Repository#1]
https://github.com/soliditylabs/ZTM-Solidity-Code-Repository/blob/e78b6b7b9aa221f915cf165347a3011528f3532d/contracts/StableCoin.sol#L146

Hi, I am following along the Zero to Mastery blockchain bootcamp and I think I found a possible mistake.

I think that instead of using 
  WadLib.fromFraction(depositorCoin.totalSupply(), surplusInUsd), 
we should use
  WadLib.fromFraction(surplusInUsd, depositorCoin.totalSupply()),

**Comment by gorgos** [comment]
Think of it more as a 1 USD = ... DPC price, not  1 DPC = ... USD. I guess it's a bit confusing, but I preferred to have less division operations later on.
